import { hitCoda, Result } from '../utils'

export default async function ff(id: number): Promise<Result> {
  const jwt1 = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkeW5hbWljU2t1SW5mbyI6IntcInNrdUlkXCI6XCJJRFJfMTAwMDBcIixcImV2ZW50UGFja2FnZVwiOlwiMFwiLFwiZGVub21JbWFnZVVybFwiOlwiXCIsXCJkZW5vbU5hbWVcIjpcIjcwIERpYW1vbmRzXCIsXCJkZW5vbUNhdGVnb3J5TmFtZVwiOlwiXCIsXCJ0YWdzXCI6W10sXCJjb3VudHJ5Mk5hbWVcIjpcIklEXCIsXCJsdnRJZFwiOjIxNyxcImRlZmF1bHRQcmljZVwiOjAuMCxcImRlZmF1bHRDdXJyZW5jeVwiOlwiXCIsXCJhZGRpdGlvbmFsSW5mb1wiOntcIkxveWFsdHlDdXJyZW5jeURldGFpbFwiOlwie1xcXCJwcmljaW5nU2NoZW1lXFxcIjpcXFwicGFpZF9jdXJyZW5jeVxcXCIsXFxcImxveWFsdHlFYXJuZWRBbW91bnRcXFwiOjAuMCxcXFwibG95YWx0eUJ1cm5lZEFtb3VudFxcXCI6MC4wfVwifX0iLCJpYXQiOjE3Njk5MjU3NjUsImV4cCI6MTc3MDE4NDk2NX0.tf-dTMOwqopmaoQTAx6SGWDsEVRGnphr9xXAiskNFfg'
  const jwt2 = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkeW5hbWljU2t1SW5mbyI6IntcInBjSWRcIjoyMjcsXCJwY05hbWVcIjpcIkdPX1BBWVwiLFwicHJpY2VcIjoxMDAwMC4wLFwiY3VycmVuY3lcIjpcIklEUlwiLFwiYXBpUHJpY2VcIjoxMDAwMC4wLFwiYXBpUHJpY2VDdXJyZW5jeVwiOlwiSURSXCIsXCJkaXNjb3VudFByaWNlXCI6MTAwMDAuMCxcInByaWNlQmVmb3JlVGF4XCI6MTAwMDAuMCxcInRheEFtb3VudFwiOjAuMCxcInNrdUlkXCI6XCJJRFJfMTAwMDBcIixcImx2dElkXCI6MjE3LFwic3BvbnNvcmVkUHJvbW9JZFwiOm51bGx9IiwiaWF0IjoxNzY5OTI1NzY1LCJleHAiOjE3NzAxODQ5NjV9.j2VpYlVNXxU9nhvHsMH3uHa2vRac3d3ju9--M19Kfno'
  const body = `user.userId=${id}&voucherPricePoint.price=10000&lvtId=217&shopLang=id_ID&voucherTypeName=FREEFIRE&dynamicSkuToken=${jwt1}&pricePointDynamicSkuToken=${jwt2}`
  const data = await hitCoda(body)
  return {
    success: true,
    game: 'Garena Free Fire',
    id,
    name: data.confirmationFields.username
  }
}